#!/usr/bin/expect

set timeout 1000
set email "$env(METEOR_EMAIL)"
set password "$env(METEOR_PASSWORD)"

cd meteor-app

spawn meteor deploy --delete $env(METEOR_DEPLOY_URL)

expect -- "*Email:"
send "$email\n"
expect -- "*assword:"
send -- "$password\n"
expect -- "Deleted."

spawn meteor deploy $env(METEOR_DEPLOY_URL) --settings settings.json

expect -- "*Email:"
send "$email\n"
expect -- "*assword:"
send -- "$password\n"
expect -- "*Now serving at $env(METEOR_DEPLOY_URL)"
